# Generated by Django 5.0.4 on 2024-04-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=48, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='category/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=48, verbose_name='نام دبیر')),
                ('image', models.ImageField(upload_to='teachers/', verbose_name='عکس')),
                ('experience', models.CharField(max_length=48, verbose_name='سابقه')),
                ('price', models.PositiveBigIntegerField(verbose_name='هزینه تدریس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلم ها',
            },
        ),
        migrations.CreateModel(
            name='TeachersVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='movie/', verbose_name='فیلم')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='teachers.teachers', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
                'ordering': ('display_order',),
            },
        ),
    ]
