# Generated by Django 5.0.4 on 2024-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='category',
        ),
        migrations.AddField(
            model_name='teachers',
            name='category',
            field=models.ManyToManyField(related_name='teach', to='teachers.category', verbose_name='دسته بندی'),
        ),
    ]
